allowBuilds:
  "@livekit/local-inference": false
  "@mastra/core": false
  agent-browser: false
  cpu-features: false
  edgedriver: false
  esbuild: false
  geckodriver: false
  koffi: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@mastra/agent-builder@1.1.6 || 1.1.7'
  - '@mastra/ai-sdk@1.6.2 || 1.6.3'
  - '@mastra/arize@1.3.4 || 1.3.5'
  - "@mastra/clickhouse@1.12.0"
  - '@mastra/client-js@1.32.0 || 1.33.1'
  - '@mastra/core@1.51.0 || 1.52.1'
  - '@mastra/deployer@1.51.0 || 1.52.1'
  - '@mastra/editor@0.13.7 || 0.13.8'
  - '@mastra/inngest@1.8.2 || 1.8.3'
  - '@mastra/libsql@1.16.0 || 1.17.0'
  - "@mastra/livekit@0.3.0"
  - '@mastra/mcp@1.14.0 || 1.15.0'
  - '@mastra/memory@1.23.0 || 1.23.1'
  - '@mastra/observability@1.16.1 || 1.16.2'
  - '@mastra/otel-exporter@1.3.4 || 1.3.5'
  - '@mastra/pg@1.16.0 || 1.17.0'
  - '@mastra/rag@2.4.1 || 2.4.2'
  - "@mastra/redis-streams@0.3.0"
  - "@mastra/schema-compat@1.3.4"
  - '@mastra/server@1.51.0 || 1.52.1'
  - mastra@1.19.0 || 1.20.1
  - '@mastra/acp@0.4.0'
  - '@mastra/browser-viewer@0.2.1'
  - '@mastra/docker@0.5.0'
  - '@mastra/evals@1.6.0'
  - '@mastra/slack@1.5.1'
  - '@mastra/tavily@1.1.1'
